packages:
  - apps/*
  - e2e/*
  - packages/*

catalog:
  '@playwright/test': ^1.55.0
  '@react-router/dev': ^7.8.2
  '@types/better-sqlite3': ^7.6.13
  '@types/node': ^22.18.1
  '@types/react': ~19.2.0
  '@types/react-dom': ~19.1.9
  better-auth: ^1.3.23
  better-sqlite3: ^12.4.1
  isbot: ^5.1.31
  kysely: ~0.28.7
  kysely-d1: ~0.4.0
  kysely-plugin-serialize: ~0.8.2
  react: ~19.2.0
  react-dom: ~19.1.1
  react-router: ~7.8.2
  sonner: 2.0.7
  typescript: ~5.9.2
  vite: ^7.1.5
  wrangler: ^4.40.2

onlyBuiltDependencies:
  - better-sqlite3
  - workerd
