packages:
  - apps/*
  - e2e/*
  - packages/*

catalog:
  '@react-router/dev': ^7.8.2
  '@types/node': ^22.18.1
  '@types/react': ^19.1.14
  react: ^19.1.1
  sonner: 2.0.7
  typescript: ~5.9.2
  vite: ^7.1.5

onlyBuiltDependencies:
  - better-sqlite3
  - workerd
