packages:
  - apps/*
  - e2e/*
  - packages/*

catalog:
  '@react-router/dev': ^7.8.1
  '@types/node': ^24.3.0
  '@types/react': ^19.1.10
  react: ^19.1.1
  sonner: 2.0.7
  typescript: ~5.9.2
  vite: ^7.1.3

onlyBuiltDependencies:
  - workerd
