// This file is generated by icon spritesheet generator

export const iconNames = [
  'unordered-list',
  'trash',
  'refresh-3',
  'plus',
  'home',
  'file-error',
  'edit',
  'dot-grid-vertical-2x3',
  'close',
  'check-2',
] as const

export type IconName = (typeof iconNames)[number]
