// This file is generated by icon spritesheet generator

export const iconNames = [
  'unordered-list',
  'refresh-3',
  'plus',
  'home',
  'file-error',
] as const

export type IconName = (typeof iconNames)[number]
