// This file is generated by icon spritesheet generator

export const iconNames = [
  'users',
  'unordered-list',
  'trash',
  'shopping-cart',
  'refresh-3',
  'plus',
  'minus',
  'log-out',
  'home',
  'google',
  'github',
  'file-error',
  'eye',
  'eye-off',
  'edit',
  'dot-grid-vertical-2x3',
  'dollar',
  'close',
  'circle',
  'chevron-up',
  'chevron-right',
  'chevron-left',
  'chevron-down',
  'checkmark',
  'checklist-2',
  'check-2',
] as const

export type IconName = (typeof iconNames)[number]
