name: Playwright Tests

on:
  workflow_run:
    workflows: [CI]
    types: [completed]
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}

permissions:
  contents: read
  deployments: write
  packages: read

jobs:
  test:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: End-to-End Tests
    strategy:
      matrix:
        app: [lists]
        include:
          - app: lists
            app_env_secret: LISTS_LOCAL_ENV
            e2e_env_secret: LISTS_E2E_ENV
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          fetch-depth: 2

      - name: Install pnpm
        uses: pnpm/action-setup@a7487c7e89a18df4991f7f222e4898a00d66ddda # v4.1.0
        with:
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: 22

      - name: Install dependencies
        shell: bash
        run: pnpm install --frozen-lockfile --prefer-offline

      - name: Cache Turborepo
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: cache-turbo-restore
        with:
          path: .turbo
          key: ${{ runner.os }}-turbo-e2e-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-turbo-build-

      - name: Build
        run: pnpm build

      - name: Get Playwright version
        run: echo "PLAYWRIGHT_VERSION=$(node -e "console.log(require('./e2e/lists/package.json').devDependencies['@playwright/test'])")" >> $GITHUB_ENV

      - name: Cache Playwright
        uses: actions/cache@0057852bfaa89a56745cba8c7296529d2fc39830 # v4.3.0
        id: playwright-cache
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ env.PLAYWRIGHT_VERSION }}

      - name: Install Playwright browsers
        if: steps.playwright-cache.outputs.cache-hit != 'true'
        run: pnpm --filter=${{ matrix.app }}-e2e exec playwright install chromium

      - name: Migrate database
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: d1 execute lists --local --file=db/schema.sql
          workingDirectory: apps/${{ matrix.app }}

      - name: Import secrets
        run: |
          echo ${{ secrets[matrix.app_env_secret] }} | tr ' ' '\n' > apps/${{ matrix.app }}/build/server/.env
          echo ${{ secrets[matrix.e2e_env_secret] }} | tr ' ' '\n' > e2e/${{ matrix.app }}/.env

      - name: Run Playwright tests
        run: pnpm e2e --filter=${{ matrix.app }}-e2e
